#!/usr/bin/env sh
# Fenris Agent Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/huangulo/fenris/main/install-agent.sh | sh
#
# What it does:
#   1. Checks prerequisites (Docker, Docker Compose v2, Git)
#   2. Prompts for server URL, API key, server name, Docker monitoring
#   3. Detects the Docker socket GID automatically
#   4. Sparse-clones just the agent/ directory from GitHub
#   5. Writes fenris-agent.yaml and docker-compose.yml into /opt/fenris-agent/
#   6. Builds and starts the agent container
#   7. Tails the logs briefly to confirm a successful POST

set -e

REPO="https://github.com/huangulo/fenris.git"
INSTALL_DIR="/opt/fenris-agent"
BOLD='\033[1m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m'

info()    { printf "${CYAN}==>${NC} %s\n" "$*"; }
success() { printf "${GREEN}✓${NC} %s\n" "$*"; }
warn()    { printf "${YELLOW}warning:${NC} %s\n" "$*"; }
die()     { printf "${RED}error:${NC} %s\n" "$*" >&2; exit 1; }

# ── Prerequisites ─────────────────────────────────────────────────────────────

info "Checking prerequisites…"

command -v docker >/dev/null 2>&1 || die "Docker is required but not installed. See https://docs.docker.com/engine/install/"

docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is required ('docker compose' plugin). See https://docs.docker.com/compose/install/"

command -v git >/dev/null 2>&1 || die "Git is required but not installed."

success "Prerequisites OK"

# ── Prompt for configuration ──────────────────────────────────────────────────

printf "\n${BOLD}Fenris Agent Setup${NC}\n\n"

printf "Fenris server URL (e.g. http://192.168.1.10:3200): "
read -r SERVER_URL
[ -z "$SERVER_URL" ] && die "Server URL is required."

printf "API key (X-API-Key used by this agent): "
read -r API_KEY
[ -z "$API_KEY" ] && die "API key is required."

DEFAULT_NAME="$(hostname)"
printf "Server name [${DEFAULT_NAME}]: "
read -r SERVER_NAME
SERVER_NAME="${SERVER_NAME:-$DEFAULT_NAME}"

printf "Enable Docker container monitoring? [Y/n]: "
read -r DOCKER_CHOICE
case "$DOCKER_CHOICE" in
  [Nn]*) DOCKER_ENABLED="false" ;;
  *)     DOCKER_ENABLED="true"  ;;
esac

# ── Docker socket GID detection ───────────────────────────────────────────────

DOCKER_SOCKET="/var/run/docker.sock"
DOCKER_GID=""

if [ "$DOCKER_ENABLED" = "true" ]; then
  if [ -S "$DOCKER_SOCKET" ]; then
    # stat output differs between GNU (Linux) and BSD (macOS)
    if stat -c "%g" "$DOCKER_SOCKET" >/dev/null 2>&1; then
      DOCKER_GID="$(stat -c '%g' "$DOCKER_SOCKET")"
    elif stat -f "%g" "$DOCKER_SOCKET" >/dev/null 2>&1; then
      DOCKER_GID="$(stat -f '%g' "$DOCKER_SOCKET")"
    fi
    if [ -n "$DOCKER_GID" ] && [ "$DOCKER_GID" != "0" ]; then
      success "Docker socket GID: ${DOCKER_GID}"
    else
      warn "Could not determine Docker socket GID — container may lack socket access."
      DOCKER_GID=""
    fi
  else
    warn "Docker socket not found at ${DOCKER_SOCKET} — Docker monitoring may not work."
  fi
fi

# ── Create install directory ──────────────────────────────────────────────────

info "Creating ${INSTALL_DIR}…"
mkdir -p "$INSTALL_DIR"

# ── Sparse-clone just the agent/ directory ────────────────────────────────────

CLONE_DIR="$INSTALL_DIR/src"

if [ -d "$CLONE_DIR/.git" ]; then
  info "Updating existing agent source…"
  git -C "$CLONE_DIR" fetch --depth=1
  git -C "$CLONE_DIR" checkout
else
  info "Cloning agent source from GitHub (sparse checkout)…"
  rm -rf "$CLONE_DIR"
  git clone \
    --filter=blob:none \
    --no-checkout \
    --depth=1 \
    "$REPO" \
    "$CLONE_DIR"
  git -C "$CLONE_DIR" sparse-checkout init --cone
  git -C "$CLONE_DIR" sparse-checkout set agent
  git -C "$CLONE_DIR" checkout
fi

success "Agent source ready"

# ── Write fenris-agent.yaml ───────────────────────────────────────────────────

info "Writing configuration…"

cat > "$INSTALL_DIR/fenris-agent.yaml" <<YAML
# Fenris Agent Configuration
# Generated by install-agent.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
server_url: "${SERVER_URL}"
api_key: "${API_KEY}"
server_name: "${SERVER_NAME}"
collect_interval: "30s"
docker_enabled: ${DOCKER_ENABLED}
disk_paths:
  - /
YAML

success "fenris-agent.yaml written"

# ── Write docker-compose.yml ──────────────────────────────────────────────────

COMPOSE_GID_LINE=""
COMPOSE_SOCKET_LINE=""
if [ "$DOCKER_ENABLED" = "true" ] && [ -n "$DOCKER_GID" ]; then
  COMPOSE_GID_LINE="    group_add:
      - \"${DOCKER_GID}\""
  COMPOSE_SOCKET_LINE="      - /var/run/docker.sock:/var/run/docker.sock:ro"
fi

cat > "$INSTALL_DIR/docker-compose.yml" <<COMPOSE
services:
  agent:
    build:
      context: ./src/agent
      dockerfile: Dockerfile
    container_name: fenris-agent
    restart: unless-stopped
    volumes:
      - ./fenris-agent.yaml:/app/fenris-agent.yaml:ro
COMPOSE

if [ "$DOCKER_ENABLED" = "true" ] && [ -n "$DOCKER_GID" ]; then
  cat >> "$INSTALL_DIR/docker-compose.yml" <<COMPOSE
      - /var/run/docker.sock:/var/run/docker.sock:ro
    group_add:
      - "${DOCKER_GID}"
COMPOSE
fi

success "docker-compose.yml written"

# ── Build and start ───────────────────────────────────────────────────────────

info "Building agent image (this may take a minute)…"
docker compose -f "$INSTALL_DIR/docker-compose.yml" build --quiet

info "Starting agent…"
docker compose -f "$INSTALL_DIR/docker-compose.yml" up -d

# ── Verify connection ─────────────────────────────────────────────────────────

info "Waiting for first POST to server…"
VERIFIED=0
for i in $(seq 1 12); do
  sleep 5
  if docker compose -f "$INSTALL_DIR/docker-compose.yml" logs agent 2>&1 | grep -q "POSTing to"; then
    VERIFIED=1
    break
  fi
done

printf "\n"
if [ "$VERIFIED" = "1" ]; then
  success "Agent is running and connected to ${SERVER_URL}"
else
  warn "Could not confirm connection within 60 s — check logs:"
  printf "  docker compose -f %s/docker-compose.yml logs -f agent\n" "$INSTALL_DIR"
fi

# ── Done ──────────────────────────────────────────────────────────────────────

printf "\n${BOLD}${GREEN}Fenris agent deployed!${NC}\n"
printf "  Server name : ${CYAN}%s${NC}\n" "$SERVER_NAME"
printf "  Server URL  : ${CYAN}%s${NC}\n" "$SERVER_URL"
printf "  Install dir : ${CYAN}%s${NC}\n" "$INSTALL_DIR"
printf "\nUseful commands:\n"
printf "  Logs   : docker compose -f %s/docker-compose.yml logs -f agent\n" "$INSTALL_DIR"
printf "  Stop   : docker compose -f %s/docker-compose.yml down\n" "$INSTALL_DIR"
printf "  Update : curl -fsSL https://raw.githubusercontent.com/huangulo/fenris/main/install-agent.sh | sh\n"
printf "\n"
